"""Business concept to database table mapping."""

CONCEPT_TO_TABLES: dict[str, list[str]] = {
    # Captacion
    "tasas de captacion": ["gold.tasas_interes_captacion"],
    "tasa de captacion": ["gold.tasas_interes_captacion"],
    "tasa captacion": ["gold.tasas_interes_captacion"],
    "captacion": ["gold.tasas_interes_captacion"],
    "cdt": ["gold.tasas_interes_captacion"],
    "cdat": ["gold.tasas_interes_captacion"],
    "cuenta de ahorro": ["gold.tasas_interes_captacion"],
    "cuentas de ahorro": ["gold.tasas_interes_captacion"],
    "ahorro": ["gold.tasas_interes_captacion"],
    "deposito": ["gold.tasas_interes_captacion"],
    "depositos": ["gold.tasas_interes_captacion"],
    # Credito (tasas)
    "tasas de credito": ["gold.tasas_interes_credito"],
    "tasa de credito": ["gold.tasas_interes_credito"],
    "tasas de colocacion": ["gold.tasas_interes_credito"],
    "tasa de colocacion": ["gold.tasas_interes_credito"],
    "colocacion": ["gold.tasas_interes_credito"],
    "desembolso": ["gold.tasas_interes_credito"],
    "desembolsos": ["gold.tasas_interes_credito"],
    "tasa efectiva": ["gold.tasas_interes_credito"],
    "credito de consumo": ["gold.tasas_interes_credito"],
    "credito comercial": ["gold.tasas_interes_credito"],
    "credito de vivienda": ["gold.tasas_interes_credito"],
    "leasing": ["gold.tasas_interes_credito"],
    "vehiculo": ["gold.tasas_interes_credito"],
    "libre inversion": ["gold.tasas_interes_credito"],
    # Cartera (saldos)
    "participacion": ["gold.distribucion_cartera"],
    "participacion de mercado": ["gold.distribucion_cartera"],
    "distribucion de cartera": ["gold.distribucion_cartera"],
    "distribucion cartera": ["gold.distribucion_cartera"],
    "cartera": ["gold.distribucion_cartera"],
    "saldo cartera": ["gold.distribucion_cartera"],
    "saldo de cartera": ["gold.distribucion_cartera"],
    "cartera comercial": ["gold.distribucion_cartera"],
    "cartera de consumo": ["gold.distribucion_cartera"],
    "cartera consumo": ["gold.distribucion_cartera"],
    "vivienda": ["gold.distribucion_cartera", "gold.tasas_interes_credito"],
    "microcredito": ["gold.distribucion_cartera"],
    # Conceptos que aplican a credito Y cartera
    "libranza": ["gold.tasas_interes_credito", "gold.distribucion_cartera"],
    "tarjeta de credito": ["gold.tasas_interes_credito", "gold.distribucion_cartera"],
    "tarjetas de credito": ["gold.tasas_interes_credito", "gold.distribucion_cartera"],
    # Entidades (dimension)
    "banco": ["gold.banco"],
    "bancos": ["gold.banco"],
    "entidad": ["gold.banco"],
    "entidades": ["gold.banco"],
    # General tasas (ambas tablas)
    "tasas de interes": ["gold.tasas_interes_captacion", "gold.tasas_interes_credito"],
    "tasa de interes": ["gold.tasas_interes_captacion", "gold.tasas_interes_credito"],
    "credito": ["gold.tasas_interes_credito", "gold.distribucion_cartera"],
    # English terms
    "interest rate": ["gold.tasas_interes_captacion", "gold.tasas_interes_credito"],
    "interest rates": ["gold.tasas_interes_captacion", "gold.tasas_interes_credito"],
    "market share": ["gold.distribucion_cartera"],
    "credit portfolio": ["gold.distribucion_cartera"],
    "loan": ["gold.tasas_interes_credito"],
    # =========================================================================
    # Clientes - General
    # =========================================================================
    "clientes": ["gold.adl_clientes_pn", "gold.adl_clientes_pj"],
    "cliente": ["gold.adl_clientes_pn", "gold.adl_clientes_pj"],
    "base de clientes": ["gold.adl_clientes_pn", "gold.adl_clientes_pj"],
    "persona natural": ["gold.adl_clientes_pn", "gold.adl_sica_clientes_pn"],
    "persona juridica": ["gold.adl_clientes_pj", "gold.adl_sica_clientes_pj"],
    "personas naturales": ["gold.adl_clientes_pn", "gold.adl_sica_clientes_pn"],
    "personas juridicas": ["gold.adl_clientes_pj", "gold.adl_sica_clientes_pj"],
    # Clientes - Demograficos PN
    "genero": ["gold.adl_clientes_pn"],
    "departamento": ["gold.adl_clientes_pn"],
    "edad": ["gold.adl_clientes_pn"],
    "rango de edad": ["gold.adl_clientes_pn"],
    "vinculacion": ["gold.adl_clientes_pn", "gold.adl_clientes_pj"],
    "segmentacion": ["gold.adl_clientes_pn"],
    "segmentacion aval": ["gold.adl_clientes_pn"],
    "ingresos": ["gold.adl_clientes_pn"],
    "salario": ["gold.adl_clientes_pn"],
    # Clientes - Corporativos PJ
    "empresa": ["gold.adl_clientes_pj", "gold.adl_sica_clientes_pj"],
    "empresas": ["gold.adl_clientes_pj", "gold.adl_sica_clientes_pj"],
    "empleados": ["gold.adl_clientes_pj"],
    "segmento ventas": ["gold.adl_clientes_pj"],
    "gobierno": ["gold.adl_sica_clientes_pj"],
    # =========================================================================
    # SICA - Productos financieros a nivel de cliente
    # =========================================================================
    "sica": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "productos financieros": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "productos del cliente": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "calificacion crediticia": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "calificacion": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "mora": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "dias de mora": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "obligaciones": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "depositos cliente": ["gold.adl_sica_clientes_pn", "gold.adl_sica_clientes_pj"],
    "cuenta nomina": ["gold.adl_sica_clientes_pn"],
    "nomina": ["gold.adl_sica_clientes_pn"],
    "factoring": ["gold.adl_sica_clientes_pj"],
    "sobregiro": ["gold.adl_sica_clientes_pj"],
}
